// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package dbLayer

import (
	"time"
)

type Book struct {
	BookID   int64
	Title    string
	Author   string
	Year     int64
	Genre    string
	Isbn     string
	Rating   float64
	Readers  int64
	Quantity int64
	Sqltime  time.Time
	Validity string
}

type Reservation struct {
	ReservationID int64
	Uname         string
	Title         string
	Sqltime       time.Time
	Validity      string
}

type Transaction struct {
	TransactionID   int64
	Uname           string
	Title           string
	TransactionType string
	Sqltime         time.Time
	Validity        string
}

type User struct {
	UserID      int64
	Uname       string
	PasswdHash  string
	Email       string
	FirstName   string
	LastName    string
	UserType    string
	ActionsLeft int64
	Sqltime     time.Time
	Validity    string
}
